ci: fix publish_docker_images
'tags' needs to be a comma separated string.

Was failing with -
 /usr/bin/docker buildx imagetools create 860592944260.dkr.ecr.us-east-2.amazonaws.com/quickwit:vega_edge-amd64 860592944260.dkr.ecr.us-east-2.amazonaws.com/quickwit:vega_edge-arm64 --tag=860592944260.dkr.ecr.us-east-2.amazonaws.com/quickwit:main-54132dca28a264130ecca619228bee56d38ac706
  860592944260.dkr.ecr.us-east-2.amazonaws.com/quickwit:vega_edge
  ERROR: invalid reference format